; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[platformio]
default_envs = esplolin_c3_mini32dev
;default_envs = esp32-s3-devkitc-1
;default_envs = esp32dev

[env:esplolin_c3_mini32dev]
board = lolin_c3_mini
board_build.partitions = no_ota.csv
build_flags =
    -DARDUINO_USB_MODE=1
    -DARDUINO_USB_CDC_ON_BOOT=1

[env:esp32-s3-devkitc-1]
board = esp32-s3-devkitc-1
build_flags =
    -DARDUINO_USB_MODE=1
    -DARDUINO_USB_CDC_ON_BOOT=1
    -DARDUINO_USB_MSC_ON_BOOT=0
    -DARDUINO_USB_DFU_ON_BOOT=0
[env:esp32dev]
board = esp32dev

[env]
platform = espressif32
framework = arduino
monitor_speed = 115200
lib_deps = 
    me-no-dev/ESPAsyncWebServer@^3.6.0
    miguelbalboa/MFRC522@^1.4.12
